services:
  db:
    container_name: loomi-db
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}

  backend:
    container_name: nestjs_project
    build: 
      dockerfile: Dockerfile
    ports:
      - '8000:3000'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://${DB_USERNAME}:${DB_PASSWORD}@db/${DB_NAME}
